type: tensorflow # python/tensorflow
py_version: 3.6.9
gpu:
  cuda: none # none / some version
  cudnn: none # none / some version
protobuf_path: <string>  # path to a protobuf file (required if using gRPC)
python_path: <string>  # path to the root of your Python folder that will be appended to PYTHONPATH (default: folder containing cortex.yaml)
dependencies:
  pip: <string>  # relative path to requirements.txt (default: requirements.txt)
  conda: <string>  # relative path to conda-packages.txt (default: conda-packages.txt)
  shell: <string>  # relative path to a shell script for system package installation (default: dependencies.sh)
multi_model_reloading:  # use this to serve one or more models with live reloading (optional)
  path: <string> # S3 path to an exported model directory (e.g. s3://my-bucket/exported_model/) (either this, 'dir', or 'paths' must be provided if 'multi_model_reloading' is specified)
  paths:  # list of S3 paths to exported model directories (either this, 'dir', or 'path' must be provided if 'multi_model_reloading' is specified)
    - name: <string>  # unique name for the model (e.g. text-generator) (required)
      path: <string>  # S3 path to an exported model directory (e.g. s3://my-bucket/exported_model/) (required)
  dir: <string>  # S3 path to a directory containing multiple models (e.g. s3://my-bucket/models/) (either this, 'path', or 'paths' must be provided if 'multi_model_reloading' is specified)
  cache_size: <int>  # the number models to keep in memory (optional; all models are kept in memory by default)
  disk_cache_size: <int>  # the number of models to keep on disk (optional; all models are kept on disk by default)
server_side_batching:  # (optional)
  max_batch_size: 4  # the maximum number of requests to aggregate before running inference
  batch_interval: 0.3  # the maximum amount of time to spend waiting for additional requests before running inference on the batch of requests
processes_per_replica: 2  # the number of parallel serving processes to run on each replica (default: 1)
threads_per_process: 2  # the number of threads per process (default: 1)
max_replica_concurrency: 4 # max concurrency
config:
  # <string: value>  # arbitrary dictionary passed to the constructor of the Handler class (optional)
env:
  # <string: string>  # dictionary of environment variables
log_level: <string>  # log level that can be "debug", "info", "warning" or "error" (default: "info")
dev: true
