type: tensorflow
py_version: 3.6.9
path: handler.py
models:
  path: s3://cortex-examples/tensorflow/image-classifier/inception/
server_side_batching:
  max_batch_size: 2
  batch_interval_seconds: 20.0 # set to an absurdly large value to show how the server-side batching works
threads_per_process: 2
# tfs_container_dns: tfs # only necessary when developing locally using containers/docker-compose; for K8s pods, this is not necessary
