type: tensorflow
py_version: 3.6.9
path: handler.py
models:
  paths:
    - name: inception
      path: s3://cortex-examples/tensorflow/image-classifier/inception/
    - name: iris
      path: s3://cortex-examples/tensorflow/iris-classifier/nn/
    - name: resnet50
      path: s3://cortex-examples/tensorflow/resnet50/
  cache_size: 1
  disk_cache_size: 2
config:
  models:
    iris:
      labels: ["setosa", "versicolor", "virginica"]
    resnet50:
      input_shape: [224, 224]
      input_key: input
      output_key: output
    inception:
      input_shape: [224, 224]
      input_key: images
      output_key: classes
  image-classifier-classes: https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json
use_local_cortex_libs: true
tfs_container_dns: tfs
